### ISSUE TITLE
Not working on automated tag deploy

### ISSUE THREAD

**Issue by lorenzo93** [SiqiLu/dotnet-bump-version#24]
Hi,

I'm using your action from a couple of weeks. It has been working like a charm.

Today I've changed my action file to be automatically triggered by a tag on a specific commit and the action gives an error and failed the execution.

Here you can find the snipped of the action file:
```
            - name: Bump versions
              uses: SiqiLu/dotnet-bump-version@master
              with:
                  version_files: "**/*.csproj"
                  version_mask: 0.0.1.0
                  version_overwrite: "*.*.*.*"
                  github_token: ${{ secrets.GITHUB_TOKEN }}
```

And here you can find the log:
```
Committing changes with message "Bump versions by dotnet-bump-version.".
git status
/usr/bin/git status
HEAD detached at pre-release
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/Checker/Checker.csproj

no changes added to commit (use "git add" and/or "git commit -a")
git config user.name "lorenzo93"
/usr/bin/git config user.name "lorenzo93"
git config user.email "MY_PERSONAL_EMAIL"
/usr/bin/git config user.email "MY_PERSONAL_EMAIL"
git config pull.rebase false
/usr/bin/git config pull.rebase false
git remote add publisher ***github.com/MY_REPOSITORY.git
/usr/bin/git remote add publisher ***github.com/MY_REPOSITORY.git
git branch bump_tmp_8...f
/usr/bin/git branch bump_tmp_8...f
git merge re-release
/usr/bin/git merge re-release
merge: re-release - not something we can merge
Error: The process '/usr/bin/git' failed with exit code 1
Error: The process '/usr/bin/git' failed with exit code 1
```
